### ISSUE TITLE
Conflicting React versions

### ISSUE THREAD

**Issue by jwbackhouse** [lerna/getting-started-example#11]
I followed the instructions in the Lerna [Getting Started](https://lerna.js.org/docs/getting-started) docs - cloned the repo, checked out `prelerna`, ran `lerna bootstrap`. But when I tried running the Remix app (via the `dev` script) I got the standard React error:

```
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
...
```

The reason is that `remixapp/package.json` expects React `^17.0.2` but what's actually installed in the root `node_modules` is version `18.1.0`. This v18 is presumably coming from the dependency in the `header` and `footer` packages.

Just manually changing the `react`and `react-dom` versions specified in `remixapp/package.json` to `^18.1.0` got things working 🙂

**Comment by juristr** [comment]
Thanks for letting us know. This will be addressed shortly. I have a local version working which I'll push up to update things in this example setup :)
