### ISSUE TITLE
Missing the real world example for tests configurations?

### ISSUE THREAD

**Issue by orest22** [lerna/getting-started-example#17]
Hey, 
I was reading the [Getting started](https://lerna.js.org/docs/getting-started) guide to understand how to configure the `nx`. I don't have much experience with `nx` so I just wanted to double-check something.  

In the real world before running tests for example for `remixapp` it would require to make sure that all dependencies have been build (taking into account the jest setup in this repo).

Would you agree that nx config would need to include something like this:

```
 "test": {
      "inputs": ["default", "^prod"],
      "dependsOn": ["^build"]
    },
```

Thank you!

**Comment by fahslaj** [comment]
Hi @orest22 , this is often not the case for unit tests, as they tend to mock their dependencies. However, if you do have tests that actually need the build artifacts of the dependencies, then you are correct in that `"dependsOn": ["^build"]` would be needed.
