### ISSUE TITLE
Request: Documentation - lerna publish with yarn workspaces

### ISSUE THREAD

**Issue by nstuyvesant** [lerna/getting-started-example#24]
I apologize if I missed it somewhere but on these pages, https://github.com/lerna/lerna/tree/main/libs/commands/publish and https://lerna.js.org/docs/features/version-and-publish, I did not see anything explicit to say that `lerna publish` will translate a dependency like...
```json
{
    "dependencies": {
        "foo": "workspace:*"
    }
}
```

to...
```json
{
    "dependencies": {
        "foo": "1.0.0"
    }
}
```

I am using yarn workspaces and wanted to verify this is the case.

**Comment by fahslaj** [comment]
Yes, this is intended behavior. This translation matches how Yarn would translate it: https://yarnpkg.com/features/workspaces
