### ISSUE TITLE
[ERROR] could not build header and footer 

### ISSUE THREAD

**Issue by shivamsinghcse** [lerna/getting-started-example#28]
when run command `npx lerna run build` 
got the output
> ```
 Lerna (powered by Nx)   Ran target build for 3 projects (2s)
 
    ✔    0/2 succeeded [0 read from cache]
 
    ✖    2/2 targets failed, including the following:
         - header:build
         - footer:build
```

**Comment by fahslaj** [comment]
Hi @shivamsinghcse , I am closing this issue as I cannot reproduce the issue and it is lacking context. Feel free to follow up if you are still experiencing this problem.
