### ISSUE TITLE
[ERROR] The "useWorkspaces" option has been removed.

### ISSUE THREAD

**Issue by daniel-clover** [lerna/getting-started-example#29]
When I run 
`lerna run build` or `npx lerna run build`
I get 
`lerna notice cli v7.1.4
lerna ERR! ECONFIGWORKSPACES The "useWorkspaces" option has been removed. By default lerna will resolve your packages using your package manager's workspaces configuration. Alternatively, you can manually provide a list of package globs to be used instead via the "packages" option in lerna.json.`

Looks like the repo is set up for version 5 of lerna, so not sure how to proceed.
Thanks for your help!

**Comment by fahslaj** [comment]
Hi @daniel-clover , I've just updated the repo to use the latest version of Lerna. This should no longer happen. Thank you for bringing attention to this issue!
