### ISSUE TITLE
command lerna bootstrap not working

### ISSUE THREAD

**Issue by jethan16** [lerna/getting-started-example#6]
I cloned the repo, checked out to 'prelerna' and followed all the steps in the lerna documentation. When I try to run 'lerna bootstrap' I always get the message 'lerna info bootsrap root only'. As a result none of my packages will link.
Any help would be much appreciate - Lerna is making me want to pull my hair out right now.

**Comment by space-w-alker** [comment]
@jethan16 
* Check the `lerna.json` file and make sure `useWorkspaces` is set to false. This file is generated by the `npx lerna init` command
* Also make sure there are no dependencies in your root `package.json` 

`lerna.json`
```
{
  "$schema": "node_modules/lerna/schemas/lerna-schema.json",
  "useNx": true,
  "useWorkspaces": false,
  "version": "0.0.0",
  "packages": [
    "packages/*"
  ]
}
```

**Comment by DanielAcostaRoa** [comment]
> @jethan16
> 
>     * Check the `lerna.json` file and make sure `useWorkspaces` is set to false. This file is generated by the `npx lerna init` command
> 
>     * Also make sure there are no dependencies in your root `package.json`
> 
> 
> `lerna.json`
> 
> ```
> {
>   "$schema": "node_modules/lerna/schemas/lerna-schema.json",
>   "useNx": true,
>   "useWorkspaces": false,
>   "version": "0.0.0",
>   "packages": [
>     "packages/*"
>   ]
> }
> ```

Thanks, setting use Workspaces to false fixes it. I spent a lot of time believing that I was doing something wrong. This should be explicit in the Getting Started part of the documentation.

**Comment by defiantgoat** [comment]
@DanielAcostaRoa I agree. This should be stated in the get started text (maybe it is mentioned in the video, but I didn't watch that).

**Comment by defiantgoat** [comment]
Though useWorkspaces: true is still in the main repo's lerna.json file. So something is amiss in this getting started that needs to be further explained. https://github.com/lerna/getting-started-example/blob/main/lerna.json#L5

**Comment by juristr** [comment]
Yeah the recommended way to go with Lerna is to use npm/yarn/pnpm workspaces instead and have the `useWorkspaces: true`. This is what happens in this repo, so bootstrapping is not needed here. 

I'm about to update this repo + the video intro & tutorial on the Lerna docs. So I'll make this point more clear :). Thanks for letting us know
